// flow-typed signature: b45a6cad47db7f38f54da44be8224a41
// flow-typed version: <<STUB>>/apollo-client-preset_v^1.0.8/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-client-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-client-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-client-preset/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-client-preset/lib/index' {
  declare module.exports: $Exports<'apollo-client-preset/lib'>;
}
declare module 'apollo-client-preset/lib/index.js' {
  declare module.exports: $Exports<'apollo-client-preset/lib'>;
}
