// flow-typed signature: 4050bc527a5ca28e2f1656f3c0c4e378
// flow-typed version: <<STUB>>/express-favicon-short-circuit_v^1.1.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-favicon-short-circuit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-favicon-short-circuit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-favicon-short-circuit/example' {
  declare module.exports: any;
}

declare module 'express-favicon-short-circuit/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-favicon-short-circuit/example.js' {
  declare module.exports: $Exports<'express-favicon-short-circuit/example'>;
}
declare module 'express-favicon-short-circuit/index' {
  declare module.exports: $Exports<'express-favicon-short-circuit'>;
}
declare module 'express-favicon-short-circuit/index.js' {
  declare module.exports: $Exports<'express-favicon-short-circuit'>;
}
declare module 'express-favicon-short-circuit/test/index.spec.js' {
  declare module.exports: $Exports<'express-favicon-short-circuit/test/index.spec'>;
}
