// flow-typed signature: b05c874001d21a1c9de744a36967362e
// flow-typed version: <<STUB>>/forcedomain_v^2.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'forcedomain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'forcedomain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'forcedomain/lib/forceDomain' {
  declare module.exports: any;
}

declare module 'forcedomain/lib/redirect' {
  declare module.exports: any;
}

declare module 'forcedomain/lib/rewrite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'forcedomain/lib/forceDomain.js' {
  declare module.exports: $Exports<'forcedomain/lib/forceDomain'>;
}
declare module 'forcedomain/lib/redirect.js' {
  declare module.exports: $Exports<'forcedomain/lib/redirect'>;
}
declare module 'forcedomain/lib/rewrite.js' {
  declare module.exports: $Exports<'forcedomain/lib/rewrite'>;
}
