// flow-typed signature: 90cb706d74842736752acd37e1835a29
// flow-typed version: <<STUB>>/graphql-anywhere_v^4.2.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-anywhere'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-anywhere' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-anywhere/jest.config' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/async' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle.cjs' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle.cjs.min' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle.esm' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/graphql' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-anywhere/jest.config.js' {
  declare module.exports: $Exports<'graphql-anywhere/jest.config'>;
}
declare module 'graphql-anywhere/lib/async.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/async'>;
}
declare module 'graphql-anywhere/lib/bundle.cjs.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle.cjs'>;
}
declare module 'graphql-anywhere/lib/bundle.cjs.min.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle.cjs.min'>;
}
declare module 'graphql-anywhere/lib/bundle.esm.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle.esm'>;
}
declare module 'graphql-anywhere/lib/bundle.umd.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/bundle.umd'>;
}
declare module 'graphql-anywhere/lib/graphql.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/graphql'>;
}
declare module 'graphql-anywhere/lib/index' {
  declare module.exports: $Exports<'graphql-anywhere/lib'>;
}
declare module 'graphql-anywhere/lib/index.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib'>;
}
declare module 'graphql-anywhere/lib/utilities.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/utilities'>;
}
