// flow-typed signature: f56f2e43c8b6ba49659b6cc9ff52c611
// flow-typed version: <<STUB>>/mversion_v^1.13.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mversion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mversion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mversion/bin/cli' {
  declare module.exports: any;
}

declare module 'mversion/lib/files' {
  declare module.exports: any;
}

declare module 'mversion/lib/git' {
  declare module.exports: any;
}

declare module 'mversion/lib/scripts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mversion/bin/cli.js' {
  declare module.exports: $Exports<'mversion/bin/cli'>;
}
declare module 'mversion/index' {
  declare module.exports: $Exports<'mversion'>;
}
declare module 'mversion/index.js' {
  declare module.exports: $Exports<'mversion'>;
}
declare module 'mversion/lib/files.js' {
  declare module.exports: $Exports<'mversion/lib/files'>;
}
declare module 'mversion/lib/git.js' {
  declare module.exports: $Exports<'mversion/lib/git'>;
}
declare module 'mversion/lib/scripts.js' {
  declare module.exports: $Exports<'mversion/lib/scripts'>;
}
