// flow-typed signature: 012847a3f8cc8a0ffa137e02ab67f0b1
// flow-typed version: <<STUB>>/next-redux-saga_v^4.0.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-saga/dist/next-redux-saga.es' {
  declare module.exports: any;
}

declare module 'next-redux-saga/dist/next-redux-saga.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-redux-saga/dist/next-redux-saga.es.js' {
  declare module.exports: $Exports<'next-redux-saga/dist/next-redux-saga.es'>;
}
declare module 'next-redux-saga/dist/next-redux-saga.umd.js' {
  declare module.exports: $Exports<'next-redux-saga/dist/next-redux-saga.umd'>;
}
