// flow-typed signature: e68e8e4dd4706e07fd5482bcf1f6e879
// flow-typed version: <<STUB>>/next-i18next_v^1.2.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-i18next/dist/commonjs/components' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/components/Link' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/components/NextStaticProvider' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/config/create-config' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/config/default-config' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/create-i18next-client' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/hocs/app-with-translation' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/hocs' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/hocs/with-internals' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/middlewares' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/middlewares/next-i18next-middleware' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/router' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/router/wrap-router' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/add-subpath' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/console-message' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/is-server' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/lng-from-req' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/lng-path-corrector' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/lngs-to-load' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/redirect-without-cache' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/remove-subpath' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/subpath-from-lng' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/subpath-is-present' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/commonjs/utils/subpath-is-required' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/components' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/components/Link' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/components/NextStaticProvider' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/config/create-config' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/config/default-config' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/create-i18next-client' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/hocs/app-with-translation' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/hocs' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/hocs/with-internals' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/middlewares' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/middlewares/next-i18next-middleware' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/router' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/router/wrap-router' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/add-subpath' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/console-message' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/is-server' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/lng-from-req' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/lng-path-corrector' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/lngs-to-load' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/redirect-without-cache' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/remove-subpath' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/subpath-from-lng' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/subpath-is-present' {
  declare module.exports: any;
}

declare module 'next-i18next/dist/es/utils/subpath-is-required' {
  declare module.exports: any;
}

declare module 'next-i18next/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-i18next/dist/commonjs/components/index' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/components'>;
}
declare module 'next-i18next/dist/commonjs/components/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/components'>;
}
declare module 'next-i18next/dist/commonjs/components/Link.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/components/Link'>;
}
declare module 'next-i18next/dist/commonjs/components/NextStaticProvider.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/components/NextStaticProvider'>;
}
declare module 'next-i18next/dist/commonjs/config/create-config.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/config/create-config'>;
}
declare module 'next-i18next/dist/commonjs/config/default-config.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/config/default-config'>;
}
declare module 'next-i18next/dist/commonjs/create-i18next-client.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/create-i18next-client'>;
}
declare module 'next-i18next/dist/commonjs/hocs/app-with-translation.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/hocs/app-with-translation'>;
}
declare module 'next-i18next/dist/commonjs/hocs/index' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/hocs'>;
}
declare module 'next-i18next/dist/commonjs/hocs/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/hocs'>;
}
declare module 'next-i18next/dist/commonjs/hocs/with-internals.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/hocs/with-internals'>;
}
declare module 'next-i18next/dist/commonjs/index' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs'>;
}
declare module 'next-i18next/dist/commonjs/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs'>;
}
declare module 'next-i18next/dist/commonjs/middlewares/index' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/middlewares'>;
}
declare module 'next-i18next/dist/commonjs/middlewares/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/middlewares'>;
}
declare module 'next-i18next/dist/commonjs/middlewares/next-i18next-middleware.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/middlewares/next-i18next-middleware'>;
}
declare module 'next-i18next/dist/commonjs/router/index' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/router'>;
}
declare module 'next-i18next/dist/commonjs/router/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/router'>;
}
declare module 'next-i18next/dist/commonjs/router/wrap-router.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/router/wrap-router'>;
}
declare module 'next-i18next/dist/commonjs/utils/add-subpath.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/add-subpath'>;
}
declare module 'next-i18next/dist/commonjs/utils/console-message.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/console-message'>;
}
declare module 'next-i18next/dist/commonjs/utils/index' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils'>;
}
declare module 'next-i18next/dist/commonjs/utils/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils'>;
}
declare module 'next-i18next/dist/commonjs/utils/is-server.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/is-server'>;
}
declare module 'next-i18next/dist/commonjs/utils/lng-from-req.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/lng-from-req'>;
}
declare module 'next-i18next/dist/commonjs/utils/lng-path-corrector.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/lng-path-corrector'>;
}
declare module 'next-i18next/dist/commonjs/utils/lngs-to-load.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/lngs-to-load'>;
}
declare module 'next-i18next/dist/commonjs/utils/redirect-without-cache.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/redirect-without-cache'>;
}
declare module 'next-i18next/dist/commonjs/utils/remove-subpath.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/remove-subpath'>;
}
declare module 'next-i18next/dist/commonjs/utils/subpath-from-lng.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/subpath-from-lng'>;
}
declare module 'next-i18next/dist/commonjs/utils/subpath-is-present.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/subpath-is-present'>;
}
declare module 'next-i18next/dist/commonjs/utils/subpath-is-required.js' {
  declare module.exports: $Exports<'next-i18next/dist/commonjs/utils/subpath-is-required'>;
}
declare module 'next-i18next/dist/es/components/index' {
  declare module.exports: $Exports<'next-i18next/dist/es/components'>;
}
declare module 'next-i18next/dist/es/components/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/components'>;
}
declare module 'next-i18next/dist/es/components/Link.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/components/Link'>;
}
declare module 'next-i18next/dist/es/components/NextStaticProvider.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/components/NextStaticProvider'>;
}
declare module 'next-i18next/dist/es/config/create-config.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/config/create-config'>;
}
declare module 'next-i18next/dist/es/config/default-config.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/config/default-config'>;
}
declare module 'next-i18next/dist/es/create-i18next-client.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/create-i18next-client'>;
}
declare module 'next-i18next/dist/es/hocs/app-with-translation.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/hocs/app-with-translation'>;
}
declare module 'next-i18next/dist/es/hocs/index' {
  declare module.exports: $Exports<'next-i18next/dist/es/hocs'>;
}
declare module 'next-i18next/dist/es/hocs/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/hocs'>;
}
declare module 'next-i18next/dist/es/hocs/with-internals.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/hocs/with-internals'>;
}
declare module 'next-i18next/dist/es/index' {
  declare module.exports: $Exports<'next-i18next/dist/es'>;
}
declare module 'next-i18next/dist/es/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/es'>;
}
declare module 'next-i18next/dist/es/middlewares/index' {
  declare module.exports: $Exports<'next-i18next/dist/es/middlewares'>;
}
declare module 'next-i18next/dist/es/middlewares/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/middlewares'>;
}
declare module 'next-i18next/dist/es/middlewares/next-i18next-middleware.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/middlewares/next-i18next-middleware'>;
}
declare module 'next-i18next/dist/es/router/index' {
  declare module.exports: $Exports<'next-i18next/dist/es/router'>;
}
declare module 'next-i18next/dist/es/router/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/router'>;
}
declare module 'next-i18next/dist/es/router/wrap-router.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/router/wrap-router'>;
}
declare module 'next-i18next/dist/es/utils/add-subpath.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/add-subpath'>;
}
declare module 'next-i18next/dist/es/utils/console-message.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/console-message'>;
}
declare module 'next-i18next/dist/es/utils/index' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils'>;
}
declare module 'next-i18next/dist/es/utils/index.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils'>;
}
declare module 'next-i18next/dist/es/utils/is-server.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/is-server'>;
}
declare module 'next-i18next/dist/es/utils/lng-from-req.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/lng-from-req'>;
}
declare module 'next-i18next/dist/es/utils/lng-path-corrector.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/lng-path-corrector'>;
}
declare module 'next-i18next/dist/es/utils/lngs-to-load.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/lngs-to-load'>;
}
declare module 'next-i18next/dist/es/utils/redirect-without-cache.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/redirect-without-cache'>;
}
declare module 'next-i18next/dist/es/utils/remove-subpath.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/remove-subpath'>;
}
declare module 'next-i18next/dist/es/utils/subpath-from-lng.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/subpath-from-lng'>;
}
declare module 'next-i18next/dist/es/utils/subpath-is-present.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/subpath-is-present'>;
}
declare module 'next-i18next/dist/es/utils/subpath-is-required.js' {
  declare module.exports: $Exports<'next-i18next/dist/es/utils/subpath-is-required'>;
}
declare module 'next-i18next/middleware.js' {
  declare module.exports: $Exports<'next-i18next/middleware'>;
}
