// flow-typed signature: 3cdbcc4cee67cc03955ba4fb8e4f49c4
// flow-typed version: <<STUB>>/react-compound-slider_v^2.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-compound-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-compound-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-compound-slider/dist/react-compound-slider' {
  declare module.exports: any;
}

declare module 'react-compound-slider/dist/react-compound-slider.min' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Handles/Handles' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Handles' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/index.umd' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Rail' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Rail/Rail' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Slider/DiscreteScale' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Slider' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Slider/LinearScale' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Slider/modes' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Slider/Slider' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Slider/utils' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Ticks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Ticks/Ticks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Tracks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/Tracks/Tracks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/es/utils' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Handles/Handles' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Handles' {
  declare module.exports: any;
}

declare module 'react-compound-slider/index.umd' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Rail' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Rail/Rail' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Slider/DiscreteScale' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Slider' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Slider/LinearScale' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Slider/modes' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Slider/Slider' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Slider/utils' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Ticks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Ticks/Ticks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Tracks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/Tracks/Tracks' {
  declare module.exports: any;
}

declare module 'react-compound-slider/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-compound-slider/dist/react-compound-slider.js' {
  declare module.exports: $Exports<'react-compound-slider/dist/react-compound-slider'>;
}
declare module 'react-compound-slider/dist/react-compound-slider.min.js' {
  declare module.exports: $Exports<'react-compound-slider/dist/react-compound-slider.min'>;
}
declare module 'react-compound-slider/es/Handles/Handles.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Handles/Handles'>;
}
declare module 'react-compound-slider/es/Handles/index' {
  declare module.exports: $Exports<'react-compound-slider/es/Handles'>;
}
declare module 'react-compound-slider/es/Handles/index.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Handles'>;
}
declare module 'react-compound-slider/es/index' {
  declare module.exports: $Exports<'react-compound-slider/es'>;
}
declare module 'react-compound-slider/es/index.js' {
  declare module.exports: $Exports<'react-compound-slider/es'>;
}
declare module 'react-compound-slider/es/index.umd.js' {
  declare module.exports: $Exports<'react-compound-slider/es/index.umd'>;
}
declare module 'react-compound-slider/es/Rail/index' {
  declare module.exports: $Exports<'react-compound-slider/es/Rail'>;
}
declare module 'react-compound-slider/es/Rail/index.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Rail'>;
}
declare module 'react-compound-slider/es/Rail/Rail.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Rail/Rail'>;
}
declare module 'react-compound-slider/es/Slider/DiscreteScale.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider/DiscreteScale'>;
}
declare module 'react-compound-slider/es/Slider/index' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider'>;
}
declare module 'react-compound-slider/es/Slider/index.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider'>;
}
declare module 'react-compound-slider/es/Slider/LinearScale.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider/LinearScale'>;
}
declare module 'react-compound-slider/es/Slider/modes.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider/modes'>;
}
declare module 'react-compound-slider/es/Slider/Slider.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider/Slider'>;
}
declare module 'react-compound-slider/es/Slider/utils.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Slider/utils'>;
}
declare module 'react-compound-slider/es/Ticks/index' {
  declare module.exports: $Exports<'react-compound-slider/es/Ticks'>;
}
declare module 'react-compound-slider/es/Ticks/index.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Ticks'>;
}
declare module 'react-compound-slider/es/Ticks/Ticks.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Ticks/Ticks'>;
}
declare module 'react-compound-slider/es/Tracks/index' {
  declare module.exports: $Exports<'react-compound-slider/es/Tracks'>;
}
declare module 'react-compound-slider/es/Tracks/index.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Tracks'>;
}
declare module 'react-compound-slider/es/Tracks/Tracks.js' {
  declare module.exports: $Exports<'react-compound-slider/es/Tracks/Tracks'>;
}
declare module 'react-compound-slider/es/utils.js' {
  declare module.exports: $Exports<'react-compound-slider/es/utils'>;
}
declare module 'react-compound-slider/Handles/Handles.js' {
  declare module.exports: $Exports<'react-compound-slider/Handles/Handles'>;
}
declare module 'react-compound-slider/Handles/index' {
  declare module.exports: $Exports<'react-compound-slider/Handles'>;
}
declare module 'react-compound-slider/Handles/index.js' {
  declare module.exports: $Exports<'react-compound-slider/Handles'>;
}
declare module 'react-compound-slider/index' {
  declare module.exports: $Exports<'react-compound-slider'>;
}
declare module 'react-compound-slider/index.js' {
  declare module.exports: $Exports<'react-compound-slider'>;
}
declare module 'react-compound-slider/index.umd.js' {
  declare module.exports: $Exports<'react-compound-slider/index.umd'>;
}
declare module 'react-compound-slider/Rail/index' {
  declare module.exports: $Exports<'react-compound-slider/Rail'>;
}
declare module 'react-compound-slider/Rail/index.js' {
  declare module.exports: $Exports<'react-compound-slider/Rail'>;
}
declare module 'react-compound-slider/Rail/Rail.js' {
  declare module.exports: $Exports<'react-compound-slider/Rail/Rail'>;
}
declare module 'react-compound-slider/Slider/DiscreteScale.js' {
  declare module.exports: $Exports<'react-compound-slider/Slider/DiscreteScale'>;
}
declare module 'react-compound-slider/Slider/index' {
  declare module.exports: $Exports<'react-compound-slider/Slider'>;
}
declare module 'react-compound-slider/Slider/index.js' {
  declare module.exports: $Exports<'react-compound-slider/Slider'>;
}
declare module 'react-compound-slider/Slider/LinearScale.js' {
  declare module.exports: $Exports<'react-compound-slider/Slider/LinearScale'>;
}
declare module 'react-compound-slider/Slider/modes.js' {
  declare module.exports: $Exports<'react-compound-slider/Slider/modes'>;
}
declare module 'react-compound-slider/Slider/Slider.js' {
  declare module.exports: $Exports<'react-compound-slider/Slider/Slider'>;
}
declare module 'react-compound-slider/Slider/utils.js' {
  declare module.exports: $Exports<'react-compound-slider/Slider/utils'>;
}
declare module 'react-compound-slider/Ticks/index' {
  declare module.exports: $Exports<'react-compound-slider/Ticks'>;
}
declare module 'react-compound-slider/Ticks/index.js' {
  declare module.exports: $Exports<'react-compound-slider/Ticks'>;
}
declare module 'react-compound-slider/Ticks/Ticks.js' {
  declare module.exports: $Exports<'react-compound-slider/Ticks/Ticks'>;
}
declare module 'react-compound-slider/Tracks/index' {
  declare module.exports: $Exports<'react-compound-slider/Tracks'>;
}
declare module 'react-compound-slider/Tracks/index.js' {
  declare module.exports: $Exports<'react-compound-slider/Tracks'>;
}
declare module 'react-compound-slider/Tracks/Tracks.js' {
  declare module.exports: $Exports<'react-compound-slider/Tracks/Tracks'>;
}
declare module 'react-compound-slider/utils.js' {
  declare module.exports: $Exports<'react-compound-slider/utils'>;
}
