// flow-typed signature: 877c27dbd45208d4390700088169063a
// flow-typed version: <<STUB>>/sitemap_v^4.1.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sitemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sitemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sitemap/dist/cli' {
  declare module.exports: any;
}

declare module 'sitemap/dist' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/errors' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/sitemap-index' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/sitemap-item' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/sitemap-parser' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/sitemap' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/types' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'sitemap/dist/lib/xmllint' {
  declare module.exports: any;
}

declare module 'sitemap/try_lastmod' {
  declare module.exports: any;
}

declare module 'sitemap/try_lastmod2' {
  declare module.exports: any;
}

declare module 'sitemap/try.last-mod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sitemap/dist/cli.js' {
  declare module.exports: $Exports<'sitemap/dist/cli'>;
}
declare module 'sitemap/dist/index' {
  declare module.exports: $Exports<'sitemap/dist'>;
}
declare module 'sitemap/dist/index.js' {
  declare module.exports: $Exports<'sitemap/dist'>;
}
declare module 'sitemap/dist/lib/errors.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/errors'>;
}
declare module 'sitemap/dist/lib/sitemap-index.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/sitemap-index'>;
}
declare module 'sitemap/dist/lib/sitemap-item.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/sitemap-item'>;
}
declare module 'sitemap/dist/lib/sitemap-parser.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/sitemap-parser'>;
}
declare module 'sitemap/dist/lib/sitemap.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/sitemap'>;
}
declare module 'sitemap/dist/lib/types.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/types'>;
}
declare module 'sitemap/dist/lib/utils.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/utils'>;
}
declare module 'sitemap/dist/lib/xmllint.js' {
  declare module.exports: $Exports<'sitemap/dist/lib/xmllint'>;
}
declare module 'sitemap/try_lastmod.js' {
  declare module.exports: $Exports<'sitemap/try_lastmod'>;
}
declare module 'sitemap/try_lastmod2.js' {
  declare module.exports: $Exports<'sitemap/try_lastmod2'>;
}
declare module 'sitemap/try.last-mod.js' {
  declare module.exports: $Exports<'sitemap/try.last-mod'>;
}
