// flow-typed signature: 0871ab2906f1c4a6f327dd8d91dd418f
// flow-typed version: <<STUB>>/snyk_v^1.222.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snyk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snyk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snyk/dist/cli/args' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/auth' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/auth/is-authed' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/config' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/help' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/ignore' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/modules' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/monitor' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/policy' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/protect' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/protect/prompts' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/protect/tasks' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/protect/wizard' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/test/formatters/legacy-format-issue' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/test/formatters/remediation-based-format-issues' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/test' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/unpublished' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/unpublished/prune' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/unpublished/walk' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/version' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/commands/woof' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/copy' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli' {
  declare module.exports: any;
}

declare module 'snyk/dist/cli/runtime' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/alerts' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/analytics' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/api-token' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/authorization' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/bus' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/config' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/detect' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/display-policy' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/authentication-failed-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/connection-timeout-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/custom-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/failed-to-get-vulnerabilities-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/failed-to-load-policy-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/failed-to-run-test-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/file-flag-bad-input' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/internal-server-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/legacy-errors' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/misconfigured-auth-in-ci-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/missing-api-token' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/missing-targetfile-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/monitor-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/no-supported-manifests-found' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/policy-not-found-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/token-expired-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/too-many-vuln-paths' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/unsupported-feature-flag-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/errors/unsupported-package-manager-error' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/exec' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/hook' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/hotload' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/is-ci' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/isolate' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/module-info' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/modules' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/monitor' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/npm' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/package-managers' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/nodejs-plugin' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/nodejs-plugin/npm-lock-parser' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/nodejs-plugin/npm-modules-parser' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/rubygems/gemfile-lock-to-dependencies' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/rubygems' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/rubygems/inspectors/gemfile' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/rubygems/inspectors/gemspec' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/rubygems/inspectors' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/rubygems/inspectors/try-get-spec' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/plugins/types' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/print-deps' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/project-metadata' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/project-metadata/target-builders/git' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/project-metadata/types' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/apply-patch' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/dedupe-patches' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/fetch-patch' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/get-vuln-source' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/ignore' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/patch' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/patches-for-package' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/strip-versions' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/update' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/protect/write-patch-flag' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/prune' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/request' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/request/request' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/request/types' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/sln' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/snyk-test/common' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/snyk-test' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/snyk-test/legacy' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/snyk-test/run-test' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/spinner' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/sub-process' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/types' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/updater' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/user-config' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/version' {
  declare module.exports: any;
}

declare module 'snyk/dist/lib/yarn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snyk/dist/cli/args.js' {
  declare module.exports: $Exports<'snyk/dist/cli/args'>;
}
declare module 'snyk/dist/cli/commands/auth/index' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/auth'>;
}
declare module 'snyk/dist/cli/commands/auth/index.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/auth'>;
}
declare module 'snyk/dist/cli/commands/auth/is-authed.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/auth/is-authed'>;
}
declare module 'snyk/dist/cli/commands/config.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/config'>;
}
declare module 'snyk/dist/cli/commands/help.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/help'>;
}
declare module 'snyk/dist/cli/commands/ignore.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/ignore'>;
}
declare module 'snyk/dist/cli/commands/index' {
  declare module.exports: $Exports<'snyk/dist/cli/commands'>;
}
declare module 'snyk/dist/cli/commands/index.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands'>;
}
declare module 'snyk/dist/cli/commands/modules.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/modules'>;
}
declare module 'snyk/dist/cli/commands/monitor.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/monitor'>;
}
declare module 'snyk/dist/cli/commands/policy.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/policy'>;
}
declare module 'snyk/dist/cli/commands/protect/index' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/protect'>;
}
declare module 'snyk/dist/cli/commands/protect/index.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/protect'>;
}
declare module 'snyk/dist/cli/commands/protect/prompts.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/protect/prompts'>;
}
declare module 'snyk/dist/cli/commands/protect/tasks.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/protect/tasks'>;
}
declare module 'snyk/dist/cli/commands/protect/wizard.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/protect/wizard'>;
}
declare module 'snyk/dist/cli/commands/test/formatters/legacy-format-issue.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/test/formatters/legacy-format-issue'>;
}
declare module 'snyk/dist/cli/commands/test/formatters/remediation-based-format-issues.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/test/formatters/remediation-based-format-issues'>;
}
declare module 'snyk/dist/cli/commands/test/index' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/test'>;
}
declare module 'snyk/dist/cli/commands/test/index.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/test'>;
}
declare module 'snyk/dist/cli/commands/unpublished/index' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/unpublished'>;
}
declare module 'snyk/dist/cli/commands/unpublished/index.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/unpublished'>;
}
declare module 'snyk/dist/cli/commands/unpublished/prune.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/unpublished/prune'>;
}
declare module 'snyk/dist/cli/commands/unpublished/walk.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/unpublished/walk'>;
}
declare module 'snyk/dist/cli/commands/version.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/version'>;
}
declare module 'snyk/dist/cli/commands/woof.js' {
  declare module.exports: $Exports<'snyk/dist/cli/commands/woof'>;
}
declare module 'snyk/dist/cli/copy.js' {
  declare module.exports: $Exports<'snyk/dist/cli/copy'>;
}
declare module 'snyk/dist/cli/index' {
  declare module.exports: $Exports<'snyk/dist/cli'>;
}
declare module 'snyk/dist/cli/index.js' {
  declare module.exports: $Exports<'snyk/dist/cli'>;
}
declare module 'snyk/dist/cli/runtime.js' {
  declare module.exports: $Exports<'snyk/dist/cli/runtime'>;
}
declare module 'snyk/dist/lib/alerts.js' {
  declare module.exports: $Exports<'snyk/dist/lib/alerts'>;
}
declare module 'snyk/dist/lib/analytics.js' {
  declare module.exports: $Exports<'snyk/dist/lib/analytics'>;
}
declare module 'snyk/dist/lib/api-token.js' {
  declare module.exports: $Exports<'snyk/dist/lib/api-token'>;
}
declare module 'snyk/dist/lib/authorization.js' {
  declare module.exports: $Exports<'snyk/dist/lib/authorization'>;
}
declare module 'snyk/dist/lib/bus.js' {
  declare module.exports: $Exports<'snyk/dist/lib/bus'>;
}
declare module 'snyk/dist/lib/config.js' {
  declare module.exports: $Exports<'snyk/dist/lib/config'>;
}
declare module 'snyk/dist/lib/detect.js' {
  declare module.exports: $Exports<'snyk/dist/lib/detect'>;
}
declare module 'snyk/dist/lib/display-policy.js' {
  declare module.exports: $Exports<'snyk/dist/lib/display-policy'>;
}
declare module 'snyk/dist/lib/errors/authentication-failed-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/authentication-failed-error'>;
}
declare module 'snyk/dist/lib/errors/connection-timeout-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/connection-timeout-error'>;
}
declare module 'snyk/dist/lib/errors/custom-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/custom-error'>;
}
declare module 'snyk/dist/lib/errors/failed-to-get-vulnerabilities-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/failed-to-get-vulnerabilities-error'>;
}
declare module 'snyk/dist/lib/errors/failed-to-load-policy-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/failed-to-load-policy-error'>;
}
declare module 'snyk/dist/lib/errors/failed-to-run-test-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/failed-to-run-test-error'>;
}
declare module 'snyk/dist/lib/errors/file-flag-bad-input.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/file-flag-bad-input'>;
}
declare module 'snyk/dist/lib/errors/index' {
  declare module.exports: $Exports<'snyk/dist/lib/errors'>;
}
declare module 'snyk/dist/lib/errors/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors'>;
}
declare module 'snyk/dist/lib/errors/internal-server-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/internal-server-error'>;
}
declare module 'snyk/dist/lib/errors/legacy-errors.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/legacy-errors'>;
}
declare module 'snyk/dist/lib/errors/misconfigured-auth-in-ci-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/misconfigured-auth-in-ci-error'>;
}
declare module 'snyk/dist/lib/errors/missing-api-token.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/missing-api-token'>;
}
declare module 'snyk/dist/lib/errors/missing-targetfile-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/missing-targetfile-error'>;
}
declare module 'snyk/dist/lib/errors/monitor-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/monitor-error'>;
}
declare module 'snyk/dist/lib/errors/no-supported-manifests-found.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/no-supported-manifests-found'>;
}
declare module 'snyk/dist/lib/errors/policy-not-found-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/policy-not-found-error'>;
}
declare module 'snyk/dist/lib/errors/token-expired-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/token-expired-error'>;
}
declare module 'snyk/dist/lib/errors/too-many-vuln-paths.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/too-many-vuln-paths'>;
}
declare module 'snyk/dist/lib/errors/unsupported-feature-flag-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/unsupported-feature-flag-error'>;
}
declare module 'snyk/dist/lib/errors/unsupported-package-manager-error.js' {
  declare module.exports: $Exports<'snyk/dist/lib/errors/unsupported-package-manager-error'>;
}
declare module 'snyk/dist/lib/exec.js' {
  declare module.exports: $Exports<'snyk/dist/lib/exec'>;
}
declare module 'snyk/dist/lib/hook.js' {
  declare module.exports: $Exports<'snyk/dist/lib/hook'>;
}
declare module 'snyk/dist/lib/hotload.js' {
  declare module.exports: $Exports<'snyk/dist/lib/hotload'>;
}
declare module 'snyk/dist/lib/index' {
  declare module.exports: $Exports<'snyk/dist/lib'>;
}
declare module 'snyk/dist/lib/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib'>;
}
declare module 'snyk/dist/lib/is-ci.js' {
  declare module.exports: $Exports<'snyk/dist/lib/is-ci'>;
}
declare module 'snyk/dist/lib/isolate.js' {
  declare module.exports: $Exports<'snyk/dist/lib/isolate'>;
}
declare module 'snyk/dist/lib/module-info/index' {
  declare module.exports: $Exports<'snyk/dist/lib/module-info'>;
}
declare module 'snyk/dist/lib/module-info/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/module-info'>;
}
declare module 'snyk/dist/lib/modules.js' {
  declare module.exports: $Exports<'snyk/dist/lib/modules'>;
}
declare module 'snyk/dist/lib/monitor.js' {
  declare module.exports: $Exports<'snyk/dist/lib/monitor'>;
}
declare module 'snyk/dist/lib/npm.js' {
  declare module.exports: $Exports<'snyk/dist/lib/npm'>;
}
declare module 'snyk/dist/lib/package-managers.js' {
  declare module.exports: $Exports<'snyk/dist/lib/package-managers'>;
}
declare module 'snyk/dist/lib/plugins/index' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins'>;
}
declare module 'snyk/dist/lib/plugins/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins'>;
}
declare module 'snyk/dist/lib/plugins/nodejs-plugin/index' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/nodejs-plugin'>;
}
declare module 'snyk/dist/lib/plugins/nodejs-plugin/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/nodejs-plugin'>;
}
declare module 'snyk/dist/lib/plugins/nodejs-plugin/npm-lock-parser.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/nodejs-plugin/npm-lock-parser'>;
}
declare module 'snyk/dist/lib/plugins/nodejs-plugin/npm-modules-parser.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/nodejs-plugin/npm-modules-parser'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/gemfile-lock-to-dependencies.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems/gemfile-lock-to-dependencies'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/index' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/inspectors/gemfile.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems/inspectors/gemfile'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/inspectors/gemspec.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems/inspectors/gemspec'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/inspectors/index' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems/inspectors'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/inspectors/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems/inspectors'>;
}
declare module 'snyk/dist/lib/plugins/rubygems/inspectors/try-get-spec.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/rubygems/inspectors/try-get-spec'>;
}
declare module 'snyk/dist/lib/plugins/types.js' {
  declare module.exports: $Exports<'snyk/dist/lib/plugins/types'>;
}
declare module 'snyk/dist/lib/print-deps.js' {
  declare module.exports: $Exports<'snyk/dist/lib/print-deps'>;
}
declare module 'snyk/dist/lib/project-metadata/index' {
  declare module.exports: $Exports<'snyk/dist/lib/project-metadata'>;
}
declare module 'snyk/dist/lib/project-metadata/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/project-metadata'>;
}
declare module 'snyk/dist/lib/project-metadata/target-builders/git.js' {
  declare module.exports: $Exports<'snyk/dist/lib/project-metadata/target-builders/git'>;
}
declare module 'snyk/dist/lib/project-metadata/types.js' {
  declare module.exports: $Exports<'snyk/dist/lib/project-metadata/types'>;
}
declare module 'snyk/dist/lib/protect/apply-patch.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/apply-patch'>;
}
declare module 'snyk/dist/lib/protect/dedupe-patches.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/dedupe-patches'>;
}
declare module 'snyk/dist/lib/protect/fetch-patch.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/fetch-patch'>;
}
declare module 'snyk/dist/lib/protect/get-vuln-source.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/get-vuln-source'>;
}
declare module 'snyk/dist/lib/protect/ignore.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/ignore'>;
}
declare module 'snyk/dist/lib/protect/index' {
  declare module.exports: $Exports<'snyk/dist/lib/protect'>;
}
declare module 'snyk/dist/lib/protect/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect'>;
}
declare module 'snyk/dist/lib/protect/patch.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/patch'>;
}
declare module 'snyk/dist/lib/protect/patches-for-package.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/patches-for-package'>;
}
declare module 'snyk/dist/lib/protect/strip-versions.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/strip-versions'>;
}
declare module 'snyk/dist/lib/protect/update.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/update'>;
}
declare module 'snyk/dist/lib/protect/write-patch-flag.js' {
  declare module.exports: $Exports<'snyk/dist/lib/protect/write-patch-flag'>;
}
declare module 'snyk/dist/lib/prune.js' {
  declare module.exports: $Exports<'snyk/dist/lib/prune'>;
}
declare module 'snyk/dist/lib/request/index' {
  declare module.exports: $Exports<'snyk/dist/lib/request'>;
}
declare module 'snyk/dist/lib/request/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/request'>;
}
declare module 'snyk/dist/lib/request/request.js' {
  declare module.exports: $Exports<'snyk/dist/lib/request/request'>;
}
declare module 'snyk/dist/lib/request/types.js' {
  declare module.exports: $Exports<'snyk/dist/lib/request/types'>;
}
declare module 'snyk/dist/lib/sln/index' {
  declare module.exports: $Exports<'snyk/dist/lib/sln'>;
}
declare module 'snyk/dist/lib/sln/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/sln'>;
}
declare module 'snyk/dist/lib/snyk-test/common.js' {
  declare module.exports: $Exports<'snyk/dist/lib/snyk-test/common'>;
}
declare module 'snyk/dist/lib/snyk-test/index' {
  declare module.exports: $Exports<'snyk/dist/lib/snyk-test'>;
}
declare module 'snyk/dist/lib/snyk-test/index.js' {
  declare module.exports: $Exports<'snyk/dist/lib/snyk-test'>;
}
declare module 'snyk/dist/lib/snyk-test/legacy.js' {
  declare module.exports: $Exports<'snyk/dist/lib/snyk-test/legacy'>;
}
declare module 'snyk/dist/lib/snyk-test/run-test.js' {
  declare module.exports: $Exports<'snyk/dist/lib/snyk-test/run-test'>;
}
declare module 'snyk/dist/lib/spinner.js' {
  declare module.exports: $Exports<'snyk/dist/lib/spinner'>;
}
declare module 'snyk/dist/lib/sub-process.js' {
  declare module.exports: $Exports<'snyk/dist/lib/sub-process'>;
}
declare module 'snyk/dist/lib/types.js' {
  declare module.exports: $Exports<'snyk/dist/lib/types'>;
}
declare module 'snyk/dist/lib/updater.js' {
  declare module.exports: $Exports<'snyk/dist/lib/updater'>;
}
declare module 'snyk/dist/lib/user-config.js' {
  declare module.exports: $Exports<'snyk/dist/lib/user-config'>;
}
declare module 'snyk/dist/lib/version.js' {
  declare module.exports: $Exports<'snyk/dist/lib/version'>;
}
declare module 'snyk/dist/lib/yarn.js' {
  declare module.exports: $Exports<'snyk/dist/lib/yarn'>;
}
