// flow-typed signature: 1b900ec210ea3329253d73b11713c36a
// flow-typed version: <<STUB>>/uuid4_v^1.1.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid4/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid4/browser.js' {
  declare module.exports: $Exports<'uuid4/browser'>;
}
declare module 'uuid4/index' {
  declare module.exports: $Exports<'uuid4'>;
}
declare module 'uuid4/index.js' {
  declare module.exports: $Exports<'uuid4'>;
}
